module Dev.Pci.Auich.Ptr where
import Foreign.Ptr
import Foreign.Storable
import Foreign.C.Types
import Kern.KernMutex
import Sys.Audioio
import Sys.Bus
import Sys.Device
import Dev.Ic.Ac97reg
import Dev.Ic.Ac97var
import Dev.AudioIf
import Dev.Auconv

--------------------------------------------------------------------------
-- Following code is generated by struct2hs command semi-automatically. --
--------------------------------------------------------------------------
newtype {-# CTYPE "struct auich_softc" #-} AuichSoftc = AuichSoftc ()
foreign import primitive "const.offsetof(struct auich_softc, sc_intr_lock)"
  offsetOf_AuichSoftc_sc_intr_lock :: Int
foreign import primitive "const.offsetof(struct auich_softc, codec_if)"
  offsetOf_AuichSoftc_codec_if :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_spdif)"
  offsetOf_AuichSoftc_sc_spdif :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_encodings)"
  offsetOf_AuichSoftc_sc_encodings :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_spdif_encodings)"
  offsetOf_AuichSoftc_sc_spdif_encodings :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_codectype)"
  offsetOf_AuichSoftc_sc_codectype :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_modem_offset)"
  offsetOf_AuichSoftc_sc_modem_offset :: Int
foreign import primitive "const.offsetof(struct auich_softc, iot)"
  offsetOf_AuichSoftc_iot :: Int
foreign import primitive "const.offsetof(struct auich_softc, aud_ioh)"
  offsetOf_AuichSoftc_aud_ioh :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_pcm246_mask)"
  offsetOf_AuichSoftc_sc_pcm246_mask :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_pcm4)"
  offsetOf_AuichSoftc_sc_pcm4 :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_pcm6)"
  offsetOf_AuichSoftc_sc_pcm6 :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_audio_formats)"
  offsetOf_AuichSoftc_sc_audio_formats :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_modem_formats)"
  offsetOf_AuichSoftc_sc_modem_formats :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_ac97_clock)"
  offsetOf_AuichSoftc_sc_ac97_clock :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_dev)"
  offsetOf_AuichSoftc_sc_dev :: Int
foreign import primitive "const.offsetof(struct auich_softc, mix_ioh)"
  offsetOf_AuichSoftc_mix_ioh :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_codecnum)"
  offsetOf_AuichSoftc_sc_codecnum :: Int
foreign import primitive "const.offsetof(struct auich_softc, pcmo)"
  offsetOf_AuichSoftc_pcmo :: Int
foreign import primitive "const.offsetof(struct auich_softc, pcmi)"
  offsetOf_AuichSoftc_pcmi :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_audev)"
  offsetOf_AuichSoftc_sc_audev :: Int
foreign import primitive "const.offsetof(struct auich_softc, dmat)"
  offsetOf_AuichSoftc_dmat :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_dmamap_flags)"
  offsetOf_AuichSoftc_sc_dmamap_flags :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_dmas)"
  offsetOf_AuichSoftc_sc_dmas :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_lock)"
  offsetOf_AuichSoftc_sc_lock :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_sample_shift)"
  offsetOf_AuichSoftc_sc_sample_shift :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_cddmamap)"
  offsetOf_AuichSoftc_sc_cddmamap :: Int
foreign import primitive "const.offsetof(struct auich_softc, sc_sts_reg)"
  offsetOf_AuichSoftc_sc_sts_reg :: Int
foreign import primitive "const.offsetof(struct auich_softc, mici)"
  offsetOf_AuichSoftc_mici :: Int

p_AuichSoftc_sc_intr_lock :: Ptr AuichSoftc -> IO (Ptr KmutexT)
p_AuichSoftc_sc_intr_lock p = return $ plusPtr p offsetOf_AuichSoftc_sc_intr_lock
p_AuichSoftc_codec_if :: Ptr AuichSoftc -> IO (Ptr (Ptr Ac97CodecIf))
p_AuichSoftc_codec_if p = return $ plusPtr p offsetOf_AuichSoftc_codec_if
p_AuichSoftc_sc_spdif :: Ptr AuichSoftc -> IO (Ptr Bool)
p_AuichSoftc_sc_spdif p = return $ plusPtr p offsetOf_AuichSoftc_sc_spdif
p_AuichSoftc_sc_encodings :: Ptr AuichSoftc -> IO (Ptr (Ptr AudioEncodingSet))
p_AuichSoftc_sc_encodings p = return $ plusPtr p offsetOf_AuichSoftc_sc_encodings
p_AuichSoftc_sc_spdif_encodings :: Ptr AuichSoftc -> IO (Ptr (Ptr AudioEncodingSet))
p_AuichSoftc_sc_spdif_encodings p = return $ plusPtr p offsetOf_AuichSoftc_sc_spdif_encodings
p_AuichSoftc_sc_codectype :: Ptr AuichSoftc -> IO (Ptr Int)
p_AuichSoftc_sc_codectype p = return $ plusPtr p offsetOf_AuichSoftc_sc_codectype
p_AuichSoftc_sc_modem_offset :: Ptr AuichSoftc -> IO (Ptr BusSizeT)
p_AuichSoftc_sc_modem_offset p = return $ plusPtr p offsetOf_AuichSoftc_sc_modem_offset
p_AuichSoftc_iot :: Ptr AuichSoftc -> IO (Ptr BusSpaceTagT)
p_AuichSoftc_iot p = return $ plusPtr p offsetOf_AuichSoftc_iot
p_AuichSoftc_aud_ioh :: Ptr AuichSoftc -> IO (Ptr BusSpaceHandleT)
p_AuichSoftc_aud_ioh p = return $ plusPtr p offsetOf_AuichSoftc_aud_ioh
p_AuichSoftc_sc_pcm246_mask :: Ptr AuichSoftc -> IO (Ptr Word32)
p_AuichSoftc_sc_pcm246_mask p = return $ plusPtr p offsetOf_AuichSoftc_sc_pcm246_mask
p_AuichSoftc_sc_pcm4 :: Ptr AuichSoftc -> IO (Ptr Word32)
p_AuichSoftc_sc_pcm4 p = return $ plusPtr p offsetOf_AuichSoftc_sc_pcm4
p_AuichSoftc_sc_pcm6 :: Ptr AuichSoftc -> IO (Ptr Word32)
p_AuichSoftc_sc_pcm6 p = return $ plusPtr p offsetOf_AuichSoftc_sc_pcm6
p_AuichSoftc_sc_audio_formats :: Ptr AuichSoftc -> Int -> IO (Ptr AudioFormat)
p_AuichSoftc_sc_audio_formats p i = return $ plusPtr p $ offsetOf_AuichSoftc_sc_audio_formats + i * sizeOf_AudioFormat
p_AuichSoftc_sc_modem_formats :: Ptr AuichSoftc -> Int -> IO (Ptr AudioFormat)
p_AuichSoftc_sc_modem_formats p i = return $ plusPtr p $ offsetOf_AuichSoftc_sc_modem_formats + i * sizeOf_AudioFormat
p_AuichSoftc_sc_ac97_clock :: Ptr AuichSoftc -> IO (Ptr Word32)
p_AuichSoftc_sc_ac97_clock p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_ac97_clock
p_AuichSoftc_sc_dev :: Ptr AuichSoftc -> IO (Ptr DeviceT)
p_AuichSoftc_sc_dev p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_dev
p_AuichSoftc_mix_ioh :: Ptr AuichSoftc -> IO (Ptr BusSpaceHandleT)
p_AuichSoftc_mix_ioh p = return $ plusPtr p $ offsetOf_AuichSoftc_mix_ioh
p_AuichSoftc_sc_codecnum :: Ptr AuichSoftc -> IO (Ptr Int)
p_AuichSoftc_sc_codecnum p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_codecnum
p_AuichSoftc_pcmo :: Ptr AuichSoftc -> IO (Ptr AuichRing)
p_AuichSoftc_pcmo p = return $ plusPtr p $ offsetOf_AuichSoftc_pcmo
p_AuichSoftc_pcmi :: Ptr AuichSoftc -> IO (Ptr AuichRing)
p_AuichSoftc_pcmi p = return $ plusPtr p $ offsetOf_AuichSoftc_pcmi
p_AuichSoftc_sc_audev :: Ptr AuichSoftc -> IO (Ptr AudioDevice)
p_AuichSoftc_sc_audev p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_audev
p_AuichSoftc_dmat :: Ptr AuichSoftc -> IO (Ptr BusDmaTagT)
p_AuichSoftc_dmat p = return $ plusPtr p $ offsetOf_AuichSoftc_dmat
p_AuichSoftc_sc_dmamap_flags :: Ptr AuichSoftc -> IO (Ptr Int)
p_AuichSoftc_sc_dmamap_flags p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_dmamap_flags
p_AuichSoftc_sc_dmas :: Ptr AuichSoftc -> IO (Ptr (Ptr AuichDma))
p_AuichSoftc_sc_dmas p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_dmas
p_AuichSoftc_sc_lock :: Ptr AuichSoftc -> IO (Ptr KmutexT)
p_AuichSoftc_sc_lock p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_lock
p_AuichSoftc_sc_sample_shift :: Ptr AuichSoftc -> IO (Ptr Int)
p_AuichSoftc_sc_sample_shift p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_sample_shift
p_AuichSoftc_sc_cddmamap :: Ptr AuichSoftc -> IO (Ptr BusDmamapT)
p_AuichSoftc_sc_cddmamap p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_cddmamap
p_AuichSoftc_sc_sts_reg :: Ptr AuichSoftc -> IO (Ptr Int)
p_AuichSoftc_sc_sts_reg p = return $ plusPtr p $ offsetOf_AuichSoftc_sc_sts_reg
p_AuichSoftc_mici :: Ptr AuichSoftc -> IO (Ptr AuichRing)
p_AuichSoftc_mici p = return $ plusPtr p $ offsetOf_AuichSoftc_mici

newtype {-# CTYPE "struct auich_ring" #-} AuichRing = AuichRing ()
foreign import primitive "const.sizeof(struct auich_ring)"
  sizeOf_AuichRing :: Int
foreign import primitive "const.offsetof(struct auich_ring, intr)"
  offsetOf_AuichRing_intr :: Int
p_AuichRing_intr :: Ptr AuichRing -> IO (Ptr (FunPtr ((Ptr ()) -> IO ())))
p_AuichRing_intr p = return $ plusPtr p $ offsetOf_AuichRing_intr
foreign import ccall "dynamic" call_AuichRing_intr ::
  FunPtr ((Ptr ()) -> IO ()) -> (Ptr ()) -> IO ()
foreign import primitive "const.offsetof(struct auich_ring, blksize)"
  offsetOf_AuichRing_blksize :: Int
p_AuichRing_blksize :: Ptr AuichRing -> IO (Ptr Int)
p_AuichRing_blksize p = return $ plusPtr p $ offsetOf_AuichRing_blksize
foreign import primitive "const.offsetof(struct auich_ring, dmalist)"
  offsetOf_AuichRing_dmalist :: Int
p_AuichRing_dmalist :: Ptr AuichRing -> IO (Ptr (Ptr AuichDmalist))
p_AuichRing_dmalist p = return $ plusPtr p $ offsetOf_AuichRing_dmalist
foreign import primitive "const.offsetof(struct auich_ring, p)"
  offsetOf_AuichRing_p :: Int
p_AuichRing_p :: Ptr AuichRing -> IO (Ptr Word32)
p_AuichRing_p p = return $ plusPtr p $ offsetOf_AuichRing_p
foreign import primitive "const.offsetof(struct auich_ring, start)"
  offsetOf_AuichRing_start :: Int
p_AuichRing_start :: Ptr AuichRing -> IO (Ptr Word32)
p_AuichRing_start p = return $ plusPtr p $ offsetOf_AuichRing_start
foreign import primitive "const.offsetof(struct auich_ring, end)"
  offsetOf_AuichRing_end :: Int
p_AuichRing_end :: Ptr AuichRing -> IO (Ptr Word32)
p_AuichRing_end p = return $ plusPtr p $ offsetOf_AuichRing_end
foreign import primitive "const.offsetof(struct auich_ring, qptr)"
  offsetOf_AuichRing_qptr :: Int
p_AuichRing_qptr :: Ptr AuichRing -> IO (Ptr Int)
p_AuichRing_qptr p = return $ plusPtr p $ offsetOf_AuichRing_qptr
foreign import primitive "const.offsetof(struct auich_ring, arg)"
  offsetOf_AuichRing_arg :: Int
p_AuichRing_arg :: Ptr AuichRing -> IO (Ptr (Ptr ()))
p_AuichRing_arg p = return $ plusPtr p $ offsetOf_AuichRing_arg

newtype {-# CTYPE "struct auich_dma" #-} AuichDma = AuichDma ()
foreign import primitive "const.sizeof(struct auich_dma)"
  sizeOf_AuichDma :: Int
foreign import primitive "const.offsetof(struct auich_dma, size)"
  offsetOf_AuichDma_size :: Int
p_AuichDma_size :: Ptr AuichDma -> IO (Ptr CSize)
p_AuichDma_size p = return $ plusPtr p $ offsetOf_AuichDma_size
foreign import primitive "const.offsetof(struct auich_dma, segs)"
  offsetOf_AuichDma_segs :: Int
p_AuichDma_segs :: Ptr AuichDma -> Int -> IO (Ptr BusDmaSegmentT)
p_AuichDma_segs p i = return $ plusPtr p $ offsetOf_AuichDma_segs + i * sizeOf_BusDmaSegmentT
foreign import primitive "const.offsetof(struct auich_dma, nsegs)"
  offsetOf_AuichDma_nsegs :: Int
p_AuichDma_nsegs :: Ptr AuichDma -> IO (Ptr Int)
p_AuichDma_nsegs p = return $ plusPtr p $ offsetOf_AuichDma_nsegs
foreign import primitive "const.offsetof(struct auich_dma, addr)"
  offsetOf_AuichDma_addr :: Int
p_AuichDma_addr :: Ptr AuichDma -> IO (Ptr (Ptr ()))
p_AuichDma_addr p = return $ plusPtr p $ offsetOf_AuichDma_addr
foreign import primitive "const.offsetof(struct auich_dma, map)"
  offsetOf_AuichDma_map :: Int
p_AuichDma_map :: Ptr AuichDma -> IO (Ptr BusDmamapT)
p_AuichDma_map p = return $ plusPtr p $ offsetOf_AuichDma_map
foreign import primitive "const.offsetof(struct auich_dma, next)"
  offsetOf_AuichDma_next :: Int
p_AuichDma_next :: Ptr AuichDma -> IO (Ptr (Ptr AuichDma))
p_AuichDma_next p = return $ plusPtr p $ offsetOf_AuichDma_next

newtype {-# CTYPE "struct auich_dmalist" #-} AuichDmalist = AuichDmalist ()
foreign import primitive "const.sizeof(struct auich_dmalist)"
  sizeOf_AuichDmalist :: Int
foreign import primitive "const.offsetof(struct auich_dmalist, base)"
  offsetOf_AuichDmalist_base :: Int
p_AuichDmalist_base :: Ptr AuichDmalist -> IO (Ptr Word32)
p_AuichDmalist_base p = return $ plusPtr p $ offsetOf_AuichDmalist_base
foreign import primitive "const.offsetof(struct auich_dmalist, len)"
  offsetOf_AuichDmalist_len :: Int
p_AuichDmalist_len :: Ptr AuichDmalist -> IO (Ptr Word32)
p_AuichDmalist_len p = return $ plusPtr p $ offsetOf_AuichDmalist_len

newtype {-# CTYPE "struct auich_cdata" #-} AuichCdata = AuichCdata ()
foreign import primitive "const.sizeof(struct auich_cdata)"
  sizeOf_AuichCdata :: Int
foreign import primitive "const.offsetof(struct auich_cdata, ic_dmalist_pcmo)"
  offsetOf_AuichCdata_ic_dmalist_pcmo :: Int
p_AuichCdata_ic_dmalist_pcmo :: Ptr AuichCdata -> Int -> IO (Ptr AuichDmalist)
p_AuichCdata_ic_dmalist_pcmo p i = return $ plusPtr p $ offsetOf_AuichCdata_ic_dmalist_pcmo + i * sizeOf_AuichDmalist
foreign import primitive "const.offsetof(struct auich_cdata, ic_dmalist_pcmi)"
  offsetOf_AuichCdata_ic_dmalist_pcmi :: Int
p_AuichCdata_ic_dmalist_pcmi :: Ptr AuichCdata -> Int -> IO (Ptr AuichDmalist)
p_AuichCdata_ic_dmalist_pcmi p i = return $ plusPtr p $ offsetOf_AuichCdata_ic_dmalist_pcmi + i * sizeOf_AuichDmalist
foreign import primitive "const.offsetof(struct auich_cdata, ic_dmalist_mici)"
  offsetOf_AuichCdata_ic_dmalist_mici :: Int
p_AuichCdata_ic_dmalist_mici :: Ptr AuichCdata -> Int -> IO (Ptr AuichDmalist)
p_AuichCdata_ic_dmalist_mici p i = return $ plusPtr p $ offsetOf_AuichCdata_ic_dmalist_mici + i * sizeOf_AuichDmalist
